arduino_port: COM5
filter:
  enabled: true
  match_mode: per_attr
  override_rules:
  - count: 2
    max: 1
    min: 1
    name: 減少傷害
  - count: 3
    max: 1
    min: 1
    name: 增加傷害
  require_grade: DG
  rules:
  - count: 2
    max: 1
    min: 1
    name: 減少傷害
max_retries: 999999
save_captures: true
target_grade: DG
timing:
  click_enter_delay: 0.4
  ocr_delay: 0.8
